Repository Iduk-Baduk/itseats-web-rider, pull requests merged in 2025-07, with the labels that each got.

#20 [Feature] 배달 위치 보내기 및 배달 목록 보내기 API (트래픽 최적화 포함)
  package.json
  src/config/api.js
  src/hooks/useFetchOrders.jsx
  src/hooks/useMyLocation.jsx
  src/pages/delivery/Map.jsx
Labels: feature

#23 [Chore] 빌드 및 버킷 업로드 설정
  .github/workflows/deploy.yml
Labels: chore

#25 [Release] 2025-07-13 02:10
  src/App.jsx
Labels: release

#26 [Release] 2025-07-13 01:11
  src/pages/temp/Temp.jsx
Labels: release

#31 [Feature] 배달 콜 연결 및 로그인 연결
  src/config/api.js
  src/hooks/useDetailOrder.jsx
  src/hooks/useFetchOrders.jsx
  src/hooks/useMyLocation.jsx
  src/pages/delivery/CallIncoming.jsx
  src/pages/delivery/DeliveryComplete.jsx
  src/pages/delivery/DeliveryInProgress.jsx
  src/pages/delivery/DeliveryInProgress.module.css
  src/pages/delivery/DeliveryPhotoConfirm.jsx
  src/pages/delivery/GoToStore.jsx
  src/pages/delivery/Map.jsx
  src/pages/delivery/Pickup.jsx
  src/services/apiClient.js
  src/services/locationService.js
Labels: feature

#35 [Release] 2025-07-15 02:55
  public/images/landing/storeMarker.png
  src/App.jsx
  src/components/common/BasicMap.jsx
  src/components/common/BasicMap.module.css
  src/hooks/useRealtimeMyLocation.jsx
  src/pages/delivery/CallIncoming.jsx
  src/pages/delivery/DeliveryInProgress.jsx
  src/pages/delivery/DeliveryMap.jsx
  src/pages/delivery/GoToStore.jsx
  src/pages/delivery/GoToStore.module.css
  src/pages/delivery/Pickup.jsx
Labels: release

#36 [Release] 2025-07-16 22:21
  .github/workflows/deploy.yml
  README.md
Labels: release
